## Apple readiness (S59, D-114):
##
##   godot --headless --path . -s tools/apple_check.gd [-- --out=apple/READINESS.md] [--strict]
##
## What the checkout proves about the macOS build: the preset (bundle id,
## universal, versions in step with the project, the entitlements file,
## signing and notarization state), the entitlements file itself, the
## release workflow's sign-and-notarize step and the secrets it needs.
## Writes the report as Markdown; `--strict` exits 1 while a blocker stands.
class_name AppleCheck
extends SceneTree

const PRESETS := "res://export_presets.cfg"
const ENTITLEMENTS := "res://apple/entitlements.plist"
const WORKFLOW := "res://.github/workflows/release.yml"
const SECRETS: Array[String] = ["APPLE_CERTIFICATE_P12", "APPLE_CERTIFICATE_PASSWORD", "APPLE_API_KEY_P8", "APPLE_API_KEY_ID", "APPLE_API_ISSUER"]


func _init() -> void:
	var out_path := "apple/READINESS.md"
	var strict := false
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--out="):
			out_path = arg.get_slice("=", 1)
		elif arg == "--strict":
			strict = true
	var result := report()
	var file := FileAccess.open(out_path, FileAccess.WRITE)
	if file != null:
		file.store_string("\n".join(result["lines"]) + "\n")
		file.close()
	for b: String in result["blockers"]:
		print("apple check: blocker: " + b)
	print("apple check: %s, %d blockers, %d notes -> %s" % ["ready" if result["ready"] else "not ready", Array(result["blockers"]).size(), Array(result["notes"]).size(), out_path])
	quit(1 if strict and not bool(result["ready"]) else 0)


## The macOS preset's options as {key: value string}, quotes stripped.
static func macos_preset(path: String = PRESETS) -> Dictionary:
	var out: Dictionary = {}
	if not FileAccess.file_exists(path):
		return out
	var in_macos := false
	var in_options := false
	for line: String in FileAccess.get_file_as_string(path).split("\n"):
		var t := line.strip_edges()
		if t.begins_with("[preset."):
			in_options = t.ends_with(".options]")
			if not in_options:
				in_macos = false
			continue
		if t.begins_with("platform=") and t.contains("\"macOS\""):
			in_macos = true
		if not in_macos or not in_options:
			continue
		var eq := t.find("=")
		if eq <= 0:
			continue
		out[t.substr(0, eq)] = t.substr(eq + 1).trim_prefix("\"").trim_suffix("\"")
	return out


## The entitlements the plist grants: {key: true/false}.
static func entitlements(path: String = ENTITLEMENTS) -> Dictionary:
	var out: Dictionary = {}
	if not FileAccess.file_exists(path):
		return out
	var re := RegEx.new()
	re.compile("<key>([^<]+)</key>\\s*<(true|false)/>")
	for m: RegExMatch in re.search_all(FileAccess.get_file_as_string(path)):
		out[m.get_string(1)] = m.get_string(2) == "true"
	return out


static func report() -> Dictionary:
	var lines: PackedStringArray = []
	var blockers: PackedStringArray = []
	var notes: PackedStringArray = []
	var preset := macos_preset()
	var project_version := String(ProjectSettings.get_setting("application/config/version", ""))
	lines.append("# Apple readiness")
	lines.append("")
	lines.append("Generated by `tools/apple_check.gd` (S59). What the checkout proves about the macOS build, and what the live verification in `apple/CHECKLIST.md` still needs. `--strict` exits 1 while a blocker stands.")
	lines.append("")
	lines.append("## The preset")
	lines.append("")
	lines.append("| Check | State |")
	lines.append("|---|---|")
	if preset.is_empty():
		blockers.append("no macOS preset in export_presets.cfg")
	var bundle := String(preset.get("application/bundle_identifier", ""))
	lines.append("| bundle identifier | %s |" % (bundle if not bundle.is_empty() else "unset"))
	if bundle.is_empty() or bundle.split(".").size() < 3:
		blockers.append("bundle identifier must be reverse-DNS (three parts or more)")
	var arch := String(preset.get("binary_format/architecture", ""))
	lines.append("| architecture | %s |" % arch)
	if arch != "universal":
		blockers.append("architecture must be universal (x86_64 + arm64)")
	var short_version := String(preset.get("application/short_version", ""))
	var version := String(preset.get("application/version", ""))
	lines.append("| versions | preset %s / %s, project %s |" % [short_version, version, project_version])
	if short_version != project_version or version != project_version:
		blockers.append("preset versions (%s / %s) are not the project version (%s)" % [short_version, version, project_version])
	var min_x86 := String(preset.get("application/min_macos_version_x86_64", ""))
	var min_arm := String(preset.get("application/min_macos_version_arm64", ""))
	lines.append("| minimum macOS | x86_64 %s, arm64 %s |" % [min_x86 if not min_x86.is_empty() else "default", min_arm if not min_arm.is_empty() else "default"])
	var codesign := String(preset.get("codesign/codesign", "0"))
	var notarize := String(preset.get("notarization/notarization", "0"))
	lines.append("| signing in the committed preset | %s |" % {"0": "disabled (ad-hoc by Godot; a fork exports as before)", "1": "built-in (ad-hoc)", "2": "rcodesign", "3": "Xcode codesign"}.get(codesign, codesign))
	lines.append("| notarization in the committed preset | %s |" % {"0": "off (the release workflow turns it on when the secrets exist)", "2": "rcodesign", "3": "Xcode notarytool"}.get(notarize, notarize))
	if notarize == "0":
		notes.append("notarization is off in the preset by design; the release workflow enables it for a run with the APPLE_* secrets")
	var ent_file := String(preset.get("codesign/entitlements/custom_file", ""))
	lines.append("| entitlements file | %s |" % (ent_file if not ent_file.is_empty() else "unset"))
	if ent_file != ENTITLEMENTS:
		blockers.append("codesign/entitlements/custom_file must be %s" % ENTITLEMENTS)
	lines.append("")
	lines.append("## Entitlements")
	lines.append("")
	var ents := entitlements()
	if ents.is_empty():
		blockers.append("apple/entitlements.plist is missing or grants nothing")
	lines.append("| Entitlement | Granted |")
	lines.append("|---|---|")
	var keys: Array = ents.keys()
	keys.sort()
	for k: String in keys:
		lines.append("| %s | %s |" % [k, "yes" if ents[k] else "no"])
	if bool(ents.get("com.apple.security.cs.allow-jit", false)):
		notes.append("allow-jit is granted; GDScript does not need it")
	if not bool(ents.get("com.apple.security.cs.allow-unsigned-executable-memory", false)):
		blockers.append("allow-unsigned-executable-memory must be granted for Godot's renderer under the hardened runtime")
	lines.append("")
	lines.append("## The release workflow")
	lines.append("")
	var workflow := FileAccess.get_file_as_string(WORKFLOW) if FileAccess.file_exists(WORKFLOW) else ""
	var has_step := workflow.contains("Sign and notarize macOS")
	lines.append("| Check | State |")
	lines.append("|---|---|")
	lines.append("| sign-and-notarize step | %s |" % ("present" if has_step else "missing"))
	if not has_step:
		blockers.append("release.yml has no 'Sign and notarize macOS' step")
	var missing_secrets: PackedStringArray = []
	for s: String in SECRETS:
		if not workflow.contains(s):
			missing_secrets.append(s)
	lines.append("| secrets the step reads | %s |" % ", ".join(SECRETS))
	if not missing_secrets.is_empty():
		blockers.append("release.yml does not read %s" % ", ".join(missing_secrets))
	lines.append("| rcodesign | %s |" % ("installed by the step" if workflow.contains("rcodesign") else "not installed by the workflow"))
	if not workflow.contains("rcodesign"):
		blockers.append("release.yml does not install rcodesign")
	lines.append("| Godot credential overrides | %s |" % ("GODOT_MACOS_* exported" if workflow.contains("GODOT_MACOS_CODESIGN_CERTIFICATE_FILE") else "missing"))
	if not workflow.contains("GODOT_MACOS_CODESIGN_CERTIFICATE_FILE"):
		blockers.append("release.yml does not pass GODOT_MACOS_* credentials to the export")
	lines.append("")
	lines.append("Whether the five secrets exist in the repository cannot be read from a checkout: the step prints which it found at run time, and `apple/CHECKLIST.md` step 4 is where they are added.")
	lines.append("")
	lines.append("## Verdict")
	lines.append("")
	if blockers.is_empty():
		lines.append("The checkout is ready: a tag with the five secrets set produces a signed, notarized, stapled universal build. Steps 6 to 9 of the checklist need a Mac.")
	else:
		lines.append("Not ready. Blockers:")
		for b: String in blockers:
			lines.append("- " + b)
	if not notes.is_empty():
		lines.append("")
		lines.append("Notes:")
		for n: String in notes:
			lines.append("- " + n)
	return {"lines": lines, "blockers": blockers, "notes": notes, "ready": blockers.is_empty(), "preset": preset, "entitlements": ents}
