## The art status (S56, D-111):
##
##   godot --headless --path . -s tools/art_status.gd [-- --out=docs/art-status.md]
##
## Every race and enemy with its sheet (valid or not) or its documented
## placeholder, the tiles, portraits and buildings the game still generates,
## and the biome palettes, as one Markdown table set. Exits 1 when a race
## or enemy has neither a valid sheet nor `art.placeholder: "rig"`.
class_name ArtStatus
extends SceneTree


func _init() -> void:
	var out_path := "docs/art-status.md"
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--out="):
			out_path = arg.get_slice("=", 1)
	var registry := ContentRegistry.new()
	registry.load_from(ContentRegistry.BASE_ROOT, [])
	var result := report(registry)
	registry.free()
	var file := FileAccess.open(out_path, FileAccess.WRITE)
	if file != null:
		file.store_string("\n".join(result["lines"]) + "\n")
		file.close()
	for p: String in result["problems"]:
		print("art status: " + p)
	print("art status: %d races, %d enemies, %d with a sheet, %d problems -> %s" % [result["races"], result["enemies"], result["sheets"], Array(result["problems"]).size(), out_path])
	quit(0 if Array(result["problems"]).is_empty() else 1)


## What each race or enemy draws with: "sheet <id>" (valid), "sheet <id> (invalid: ...)",
## "placeholder rig" (documented), or "" (nothing said).
static func art_of(registry: ContentRegistry, entry: Dictionary) -> String:
	var art: Dictionary = entry.get("art", {})
	var sheet_id := String(art.get("sheet", ""))
	if not sheet_id.is_empty():
		var sprite: Dictionary = registry.get_entry("sprites", sheet_id)
		if sprite.is_empty():
			return "sheet %s (missing sidecar)" % sheet_id
		var sheet := SpriteSheet.load_entry(sprite)
		if sheet == null or not sheet.is_valid():
			return "sheet %s (invalid: %s)" % [sheet_id, ", ".join(sheet.errors) if sheet != null else "unreadable"]
		return "sheet %s" % sheet_id
	if String(art.get("placeholder", "")) == "rig":
		return "placeholder rig"
	return ""


static func report(registry: ContentRegistry) -> Dictionary:
	var lines: PackedStringArray = []
	var problems: PackedStringArray = []
	var sheets := 0
	lines.append("# Art status")
	lines.append("")
	lines.append("Generated by `tools/art_status.gd` (S56). What every thing on screen draws with today: a sprite sheet from `content/sprites/`, or the placeholder the game generates at runtime and says so. Real art replaces a sheet file-for-file (`docs/art-pipeline.md`); a race or enemy with neither a valid sheet nor `\"art\": {\"placeholder\": \"rig\"}` fails the validator and this tool.")
	lines.append("")
	lines.append("## Races")
	lines.append("")
	lines.append("| Race | Draws with | Overlay |")
	lines.append("|---|---|---|")
	var races := registry.get_all("races")
	for r: Dictionary in races:
		var what := art_of(registry, r)
		if what.is_empty():
			problems.append("race %s: no sheet and no documented placeholder" % r["id"])
		elif what.begins_with("sheet ") and not what.contains("("):
			sheets += 1
		var overlay: Dictionary = r.get("overlay", {})
		lines.append("| %s | %s | %s |" % [r.get("name", r["id"]), what if not what.is_empty() else "**nothing said**", overlay.get("kind", "none")])
	lines.append("")
	lines.append("## Enemies")
	lines.append("")
	lines.append("| Enemy | Family | Draws with | Colour |")
	lines.append("|---|---|---|---|")
	var enemies := registry.get_all("enemies")
	for e: Dictionary in enemies:
		var what := art_of(registry, e)
		if what.is_empty():
			problems.append("enemy %s: no sheet and no documented placeholder" % e["id"])
		elif what.begins_with("sheet ") and not what.contains("("):
			sheets += 1
		var art: Dictionary = e.get("art", {})
		lines.append("| %s | %s | %s | %s |" % [e.get("name", e["id"]), e.get("family", "?"), what if not what.is_empty() else "**nothing said**", art.get("color", "?")])
	lines.append("")
	lines.append("## Generated at runtime")
	lines.append("")
	lines.append("| What | Generator | Contract |")
	lines.append("|---|---|---|")
	lines.append("| Tiles (%d) | `PlaceholderTiles` from each tile's `art` block and the biome palette | the `art` block: shape, fill, edge, pattern, top/left/right roles, `glow` |" % registry.get_all("tiles").size())
	lines.append("| Portraits | `PlaceholderActorArt.portrait_image` from class colour, race overlay and appearance | `portrait_for(speaker)` in the world; a drawn portrait replaces it there |")
	lines.append("| Buildings (%d) | `BuildingActor` blocks from the building entry | the building entry |" % registry.get_all("buildings").size())
	lines.append("| Pickups (%d) | `PickupActor` from `art.color` | the pickup's `art` |" % registry.get_all("pickups").size())
	lines.append("| Lighting | `LightingRig`: ambient from `rules/lighting` or the palette's `ambient`, a light per tile with a `glow` role, one on the leader | `rules/lighting`, tile `art.glow` |")
	lines.append("| Screen effects | `ScreenFx` shader: glow, or glow with scanlines and a vignette | the Screen effects setting, `--fx=` |")
	lines.append("")
	lines.append("## Biome palettes")
	lines.append("")
	lines.append("| Biome | Roles |")
	lines.append("|---|---|")
	for b: Dictionary in registry.get_all("biomes"):
		var palette: Dictionary = b.get("palette", {})
		var roles: Array = palette.keys()
		roles.sort()
		lines.append("| %s | %d: %s |" % [b.get("name", b["id"]), roles.size(), ", ".join(PackedStringArray(roles))])
	lines.append("")
	lines.append("Sheets in `content/sprites/`: %d. Races: %d. Enemies: %d." % [registry.get_all("sprites").size(), races.size(), enemies.size()])
	return {"lines": lines, "problems": problems, "races": races.size(), "enemies": enemies.size(), "sheets": sheets}
