## The audio status (S57, D-112):
##
##   godot --headless --path . -s tools/audio_status.gd [-- --out=docs/audio-status.md] [--strict]
##
## Every audio entry with what plays for it (a file beside its sidecar,
## or the synthesised placeholder), where the game fires it (an event in
## rules/audio, an ability's or a tile's `sound`, the music table), as
## one Markdown table set. `--strict` exits 1 while any placeholder
## remains on a path the game fires: the release gate the plan asks for.
class_name AudioStatus
extends SceneTree


func _init() -> void:
	var out_path := "docs/audio-status.md"
	var strict := false
	for arg: String in OS.get_cmdline_user_args():
		if arg.begins_with("--out="):
			out_path = arg.get_slice("=", 1)
		elif arg == "--strict":
			strict = true
	var registry := ContentRegistry.new()
	registry.load_from(ContentRegistry.BASE_ROOT, [])
	var result := report(registry)
	registry.free()
	var file := FileAccess.open(out_path, FileAccess.WRITE)
	if file != null:
		file.store_string("\n".join(result["lines"]) + "\n")
		file.close()
	for p: String in result["problems"]:
		print("audio status: " + p)
	print("audio status: %d entries, %d from files, %d placeholders, %d unused, %d problems -> %s" % [result["entries"], result["files"], result["placeholders"], Array(result["unused"]).size(), Array(result["problems"]).size(), out_path])
	var code := 1 if not Array(result["problems"]).is_empty() else 0
	if strict and int(result["placeholders"]) > 0:
		print("audio status: --strict: %d synthesised placeholders still on a shipping path" % result["placeholders"])
		code = 1
	quit(code)


## Where an audio id is fired from: "rules/audio <group>.<event>", "music <state>[.<key>]",
## "ability <id>", "tile <id>".
static func uses_of(registry: ContentRegistry) -> Dictionary:
	var uses: Dictionary = {}
	var add := func(id: String, where: String) -> void:
		if id.is_empty():
			return
		if not uses.has(id):
			uses[id] = PackedStringArray()
		var list: PackedStringArray = uses[id]
		list.append(where)
		uses[id] = list
	var rules: Dictionary = registry.get_entry("rules", "audio")
	for group: String in rules:
		var block: Variant = rules[group]
		if not block is Dictionary:
			continue
		if group == "music":
			for state: String in (block as Dictionary):
				var v: Variant = (block as Dictionary)[state]
				if v is String:
					add.call(String(v), "music %s" % state)
				elif v is Dictionary:
					for key: String in (v as Dictionary):
						add.call(String((v as Dictionary)[key]), "music %s.%s" % [state, key])
			continue
		for event: String in (block as Dictionary):
			var target: Variant = (block as Dictionary)[event]
			if target is String:
				add.call(String(target), "rules/audio %s.%s" % [group, event])
	for a: Dictionary in registry.get_all("abilities"):
		add.call(String(a.get("sound", "")), "ability %s" % a["id"])
	for t: Dictionary in registry.get_all("tiles"):
		add.call(String(t.get("sound", "")), "tile %s" % t["id"])
	return uses


static func source_of(entry: Dictionary) -> String:
	var file := String(entry.get("file", ""))
	if file.is_empty():
		return "synth placeholder"
	var path := String(entry.get("_path", "")).get_base_dir().path_join(file)
	if FileAccess.file_exists(path) or ResourceLoader.exists(path):
		return "file %s" % file
	return "file %s (missing: the synth plays)" % file


static func report(registry: ContentRegistry) -> Dictionary:
	var lines: PackedStringArray = []
	var problems: PackedStringArray = []
	var unused: PackedStringArray = []
	var files := 0
	var placeholders := 0
	var uses := uses_of(registry)
	lines.append("# Audio status")
	lines.append("")
	lines.append("Generated by `tools/audio_status.gd` (S57). Every audio entry, what plays for it today and where the game fires it. A recorded file beside the sidecar with `\"file\"` in the entry replaces the synth without a code change (`docs/audio-pipeline.md`); `--strict` fails while any placeholder is still fired, which is the 1.0 gate.")
	lines.append("")
	for kind: String in ["music", "sfx"]:
		lines.append("## %s" % ("Music" if kind == "music" else "Sound effects"))
		lines.append("")
		lines.append("| Entry | Plays | Fired from | Volume |")
		lines.append("|---|---|---|---|")
		for a: Dictionary in registry.get_all("audio"):
			if String(a.get("kind", "")) != kind:
				continue
			var id := String(a["id"])
			var source := source_of(a)
			if source.begins_with("file ") and not source.contains("(missing"):
				files += 1
			else:
				placeholders += 1
			if source.contains("(missing"):
				problems.append("%s: %s" % [id, source])
			var where: PackedStringArray = uses.get(id, PackedStringArray())
			if where.is_empty():
				unused.append(id)
			lines.append("| %s (%s) | %s | %s | %s dB |" % [a.get("name", id), id, source, ", ".join(where) if not where.is_empty() else "nothing (unused)", a.get("volume_db", 0)])
		lines.append("")
	lines.append("## Fired but missing")
	lines.append("")
	var missing: PackedStringArray = []
	for id: String in uses:
		if not registry.has_entry("audio", id):
			missing.append("%s (%s)" % [id, ", ".join(uses[id])])
			problems.append("%s is fired but has no audio entry" % id)
	lines.append("none" if missing.is_empty() else "\n".join(missing))
	lines.append("")
	lines.append("Entries: %d. From files: %d. Synth placeholders: %d. Unused: %s." % [registry.get_all("audio").size(), files, placeholders, ", ".join(unused) if not unused.is_empty() else "none"])
	return {"lines": lines, "problems": problems, "unused": unused, "entries": registry.get_all("audio").size(), "files": files, "placeholders": placeholders}
